from django.urls import path
from .views import (
    HomeView,
    ProductListView,
    ProductDetailView,
    CartView,
    OrderSummaryView,
    PaymentView,
    PaymentSuccessView,
    CODSuccessView,
    OrderPublicSummaryView,
    PaymentFailureView,
    CreateOrderView,
    WishlistToggleView,
    ProductSearchView,
    SolutionsView,
    PromotionsView,
    AboutUsView,
    ContactView,
    AdminDashboardView,
    AdminDeliveriesView,
    AdminPromotionsView,
    AdminAddProductView,
    AdminProductListView,
    AdminUsersView,
    AdminCorporateSettingsView,
    AdminLegalPagesView,
    AdminDeleteProductView,
    AdminEditProductView,
)
from simad.payments.views import (
    PayUnitWebhookView, 
    StripeWebhookView, 
    CreateStripePaymentIntentView, 
    GetPaymentStatusView
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("solutions/", SolutionsView.as_view(), name="solutions"),
    path("promotions/", PromotionsView.as_view(), name="promotions"),
    path("about-us/", AboutUsView.as_view(), name="about-us"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("wishlist/toggle/", WishlistToggleView.as_view(), name="wishlist-toggle"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("checkout/cart/", CartView.as_view(), name="cart"),
    path("checkout/order/create/", CreateOrderView.as_view(), name="order-create"),
    path("checkout/summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("checkout/payment/", PaymentView.as_view(), name="payment"),
    path("checkout/success/cod/", CODSuccessView.as_view(), name="cod-success"),
    path("orders/summary/<str:reference>/", OrderPublicSummaryView.as_view(), name="order-public-summary"),
    path("checkout/completed/", PaymentSuccessView.as_view(), name="payment-success"),
    path("checkout/failure/", PaymentFailureView.as_view(), name="payment-failure"),
    path("payments/payunit/webhook/", PayUnitWebhookView.as_view(), name="payunit-webhook"),
    path("payments/stripe/webhook/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("payments/stripe/create-intent/", CreateStripePaymentIntentView.as_view(), name="stripe-create-intent"),
    path("payments/status/", GetPaymentStatusView.as_view(), name="payment-status"),
    path("api/search/", ProductSearchView.as_view(), name="api-search"),
    
    # Admin URLs
    path("admin-dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin-dashboard/deliveries/", AdminDeliveriesView.as_view(), name="admin-deliveries"),
    path("admin-dashboard/promotions/", AdminPromotionsView.as_view(), name="admin-promotions"),
    path("admin-dashboard/add-product/", AdminAddProductView.as_view(), name="admin-add-product"),
    path("admin-dashboard/products/", AdminProductListView.as_view(), name="admin-product-list"),
    path("admin-dashboard/users/", AdminUsersView.as_view(), name="admin-users"),
    path("admin-dashboard/settings/", AdminCorporateSettingsView.as_view(), name="admin-settings"),
    path("admin-dashboard/legal/", AdminLegalPagesView.as_view(), name="admin-legal-pages"),
    path("admin-dashboard/edit-product/<uuid:pk>/", AdminEditProductView.as_view(), name="admin-edit-product"),
    path("admin-dashboard/delete-product/<uuid:pk>/", AdminDeleteProductView.as_view(), name="admin-delete-product"),
]
