# Generated by Django 5.2.6 on 2026-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clinical_notes',
            field=models.TextField(blank=True, default='', verbose_name='Clinical Notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='precautions',
            field=models.TextField(blank=True, default='', verbose_name='Precautions'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Technical Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.JSONField(blank=True, default=list, verbose_name='Usage Instructions'),
        ),
    ]
