# Generated by Django 5.2.6 on 2026-03-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_clinical_notes_product_precautions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Initial Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock Quantity'),
        ),
    ]
