# Generated by Django 5.2.6 on 2026-04-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='order_qrcodes/', verbose_name='Order QR Code'),
        ),
    ]
